settings_version: 0.0.4
datasets_dir: /home/app/datasets
weights_dir: weights
runs_dir: runs
uuid: c85160f49cf23d785357b15c0687605bb7b78e1831607ae79634e3028626aa55
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
