name: Build (frontend)

on:
  workflow_run:
    branches: ["dev"]
    workflows: [Check Style (frontend)]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build/push API (dev)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          target: development
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:frontend-dev
      - name: Build/push API (prod)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          target: production
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:frontend-latest
