name: Code (test and build)

on:
  push:
    branches: ["dev"]
  workflow_dispatch:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "./scripts/test-ci.sh"
  build_api:
    needs: test_api
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build/push API (dev)
        uses: docker/build-push-action@v4
        with:
          context: ./api
          target: development
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:api-dev
      - name: Build/push API (prod)
        uses: docker/build-push-action@v4
        with:
          context: ./api
          target: production
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:api-latest
  build_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build/push API (dev)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          target: development
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:frontend-dev
      - name: Build/push API (prod)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          target: production
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:frontend-latest
